refresh_token=eXVpt9CRM4GfZS4UnnnN5DoiTmYmb+3/l533faGXvQZYAu/BGRsPu7BQb1OBaEyvMpaLOS4Sqd19NoJrDZaSNdRIaRo0Zo8iGuvXvYbyuMfBdKo6YkPBWr9qFQe51lRYOVN4ccWelrDUIExCw7L6E6oFpbmcnoWgAFz+i6pLNKnEnmVuEDGDPaXk+Zhx7QLp
client_id=wZ8DtOwzcvg6X7ZdVV0ewTd0Is8xgGkesW1/ED4P7noFAYegzeWphyy6sJGrc+VT
client_secret=BtZ3mlXkIN0jwxjHRYsxsS1I1RPazvDOhR49/DPLhJ0FAYegzeWphyy6sJGrc+VT
baseURI=https://api.spotify.com

